version: 2.3.2.{build}

image: Visual Studio 2015
platform: x64
configuration:  # a trick to construct a build matrix with multiple Python versions
  - 3.7

environment:
  matrix:
    - COMPILER: MSVC
      TASK: sdist
    - COMPILER: MINGW
      TASK: sdist

clone_depth: 5

install:
  - ps: Write-Output("custom install scribbity bibbity")

build_script:
  - ps: Write-Output("custom build script")

test_script:
  - powershell.exe -ExecutionPolicy Bypass -File .\.ci\test_windows.ps1
