version: 2.3.2.{build}

image: Visual Studio 2015
platform: x64
configuration:  # a trick to construct a build matrix with multiple Python versions
  - 3.7

environment:
  matrix:
    - COMPILER: MSVC
      TASK: regular
    - COMPILER: MINGW
      TASK: regular
    - COMPILER: MINGW
      TASK: r-package
      R_WINDOWS_VERSION: 3.6.3

clone_depth: 5

# install:
#   script:
#     Write-Output
# build_script: null

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - powershell.exe -ExecutionPolicy Bypass -File .\.ci\test_windows.ps1
